name: Prospect.rs

exclude:   [config.ru, Gemfile, Gemfile.lock, newrelic.yml, Procfile, Procfile.local, Rakefile, README.md, vendor]
future:    false
permalink: /:year/:month/:day/:title
pygments:  true

assets:
  compress:
    css: sass
    js:  uglifier
